Setup "webpack encore" with dependence for Vue Js
yalefresne/whereat pull request #24
Opened 2020-10-17 17:16 UTC by senzowayne

2020-10-17 18:11 UTC, yalefresne commented
I request @Rantignac review cause he shared a config for webpack very interesting with me, but i don't refound  it.  
So @Rantignac, if you can share it again here ^^

2020-10-18 19:12 UTC, Rantignac commented
@yalefresne, @senzowayne, we can use the webpack encore aliases  to have namespaces in JS:https://blog.elao.com/fr/dev/webpack-encore-alias-namespace/

2020-10-18 19:36 UTC, senzowayne commented
Amazing !! 🔥 thanks for share.

2020-10-18 21:10 UTC, yalefresne commented
Yeah ! Thanks for sharing @Rantignac !  
So @senzowayne if you could set that, that will be nice ! 🚀
Globally, if you could delete all not necessary comments, but of course, you can leave that you think use later.

2020-10-20 09:42 UTC, senzowayne commented
I noticed an improvement in speed during the build (with namespace) 🔥

2020-10-21 17:18 UTC, yalefresne requested changes

2020-10-21 17:18 UTC, yalefresne commented on .gitignore
> +
You should put this lines in a personnal gitignore file.  
[https://stackoverflow.com/questions/5724455/can-i-make-a-user-specific-gitignore-file](https://stackoverflow.com/questions/5724455/can-i-make-a-user-specific-gitignore-file)

2020-10-21 17:18 UTC, yalefresne commented on assets/app.js
> +console.log('Hello Webpack Encore! Edit me in assets/app.js');
I'm not sure, we need this line ^^

2020-10-21 17:26 UTC, yalefresne requested changes

2020-10-21 17:26 UTC, yalefresne commented on assets/app.js
> +console.log('Hello Webpack Encore! Edit me in assets/app.js');
```suggestion
console.log('Hello Webpack Encore! Edit me in assets/app.js');
```
I'm not sure we need this line.

2020-10-21 19:21 UTC, yalefresne requested changes

2020-10-21 19:21 UTC, yalefresne commented on package.json
> +        "@symfony/webpack-encore": "^0.31.0",
```suggestion
        "@babel/core": "^7.12.3",
        "@symfony/webpack-encore": "^0.31.0",
```
To resolve some dependency warnings after `yarn install`

2020-10-21 19:21 UTC, yalefresne commented on package.json
> +        "core-js": "^3.0.0",
```suggestion
        "core-js": "^3.0.0",
        "css-loader": "^5.0.0",
```
To resolve `warning " > vue-loader@15.9.3" has unmet peer dependency "css-loader@*".`

2020-10-21 23:27 UTC, yalefresne approved these changes

2020-10-21 23:28 UTC, merged